// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxkyuewjpqxaloqcxwaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4a3l1ZXdqcHF4YWxvcWN4d2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTQ5MTQsImV4cCI6MjA3MDk5MDkxNH0.gUYUrTZ11h_82R8Z63eq51KxT4mchB5-jBjfLTbwhPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});